name: ArtCIPipe

on: push

new: change

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        type: git-clone
        repo: 'lentond/ArtWebsite'
        revision: main
        git: github
      - name: Build Images
        run: |
        cd ArtWebsite
        docker-compose up |
      
  BuildAndPush:
    runs-on: ubuntu-latest
    needs: Testing
    steps:
      - name: My first step
        run: echo This is the first step of my second job.
  
  job_3:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my third job.
  
  job_4:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my fourth job.
  
  job_5:
    runs-on: ubuntu-latest
    steps:
      - name: My first step
        run: echo This is the first step of my fifth job.

  
